module.exports = {
  testEnvironment: "jsdom",
  preset: "jest-expo",
  moduleFileExtensions: ["js", "ts", "tsx"],
  moduleNameMapper: {
    "^@/screens(.*)$": "<rootDir>/src/screens/$1",
    "^@/components(.*)$": "<rootDir>/src/components/$1",
    "^@/hooks(.*)$": "<rootDir>/src/hooks/$1",
    "^@/mocks(.*)$": "<rootDir>/src/mocks/$1",
    "^@/assets(.*)$": "<rootDir>/src/assets/$1",
    "^@/constants(.*)$": "<rootDir>/src/constants/$1",
    "^@/modules(.*)$": "<rootDir>/src/modules/$1",
    "^@/validations(.*)$": "<rootDir>/src/validations/$1",
    "^@/services(.*)$": "<rootDir>/src/services/$1",
    "^@/store(.*)$": "<rootDir>/src/store/$1",
    "^@/utils(.*)$": "<rootDir>/src/utils/$1",
    "^@/navigation(.*)$": "<rootDir>/src/navigation/$1",
  },
  collectCoverage: true,
  collectCoverageFrom: [
    "**/*.{js,jsx,ts,tsx}",
    "!**/coverage/**",
    "!**/node_modules/**",
    '!**/babel.config.js',
    '!**/jest.setup.js',
  ],
};
